export const MENSDATA_REQUEST = "MENSDATA_REQUEST";
export const MENSDATA_SUCCESS = "MENSDATA_SUCCESS";
export const MENSDATA_FAILURE = "MENSDATA_FAILURE";

export const CARTDATA_REQUEST = "CARTDATA_REQUEST";
export const CARTDATA_SUCCESS = "CARTDATA_SUCCESS";
export const CARTDATA_FAILURE = "CARTDATA_FAILURE";
